### ISSUE TITLE
"semodule -p" accesses files on root filesystem

### ISSUE THREAD

**Issue by ensc** [SELinuxProject/selinux#109]
I want to try build offline an SELinux policy and prepared a filesystem like

```
  ~/src/policy-root
  |--- etc/selinux/selinux/...
  |--- var/lib/selinux/minimum/...
```

Most operations work fine; e.g.

```
semodule -p ~/src/policy-root -s 'minimum' -n -i my-module.pp
semodule -p ~/src/policy-root -s 'minimum' -n -B
```

builds a (working) policy.  But it appears, the `semodule` still accesses files on the rootfs. E.g. running it through `strace` shows:

```
12457 openat(AT_FDCWD, "/etc/selinux/config", O_RDONLY|O_CLOEXEC) = 3
12457 access("/sbin/load_policy", X_OK) = 0
....
12457 openat(AT_FDCWD, "...../policy-root/var/lib/selinux/minimum/tmp/booleans.local", O_RDONLY) = 4
12457 openat(AT_FDCWD, "/etc/selinux/targeted/booleans.subs_dist", O_RDONLY|O_CLOEXEC) = 5

```

At least the last part seems to cause problems because substitution rules from host are applied to the offline policy.  Here, it removes e.g.  `allow_mount_anyfile=1` from the `booleans.local` file because host configuration contains

```
allow_mount_anyfile mount_anyfile
```

which does not exist for the offline policy.

**Comment by stephensmalley** [comment]
The problem here seems to be that libsemanage is using a libselinux interface, selinux_boolean_sub(), that internally accesses the "active" policy files, without having previously directed libselinux to an alternate root via selinux_set_policy_root().  Simplest fix would likely be to save, set, and restore the libselinux policy root around the selinux_boolean_sub() call.  More complete approach would be to call selinux_set_policy_root() when setting the semanage root but this will require changes elsewhere to retain the ability to detect when we are installing to the active policy store.

**Comment by stephensmalley** [comment]
See if the PR fixes your issue
