### ISSUE TITLE
load_policy.c:136:11: error: assignment from incompatible pointer type [-Werror]

### ISSUE THREAD

**Issue by ssbarnea** [SELinuxProject/selinux#134]
It seems that it fails to compile:
```
for lang in ru ; do \
        if [ -e ${lang}/man3 ] ; then \
                mkdir -p ~/obj/usr/share/man/${lang}/man3 ; \
                install -m 644 ${lang}/man3/*.3 ~/obj/usr/share/man/${lang}/man3 ; \
        fi ; \
        if [ -e ${lang}/man8 ] ; then \
                mkdir -p ~/obj/usr/share/man/${lang}/man8 ; \
                install -m 644 ${lang}/man8/*.8 ~/obj/usr/share/man/${lang}/man8 ; \
        fi ; \
done
make[2]: Leaving directory `/root/.cache/.rmux/selinux/libsepol/man'
make[1]: Leaving directory `/root/.cache/.rmux/selinux/libsepol'
make[1]: Entering directory `/root/.cache/.rmux/selinux/libselinux'
make[2]: Entering directory `/root/.cache/.rmux/selinux/libselinux/src'
cc -O2 -Werror -Wall -Wextra -Wmissing-format-attribute -Wmissing-noreturn -Wpointer-arith -Wshadow -Wstrict-prototypes -Wundef -Wunused -Wwrite-strings -I~/obj/usr/include -I../include -D_GNU_SOURCE  -DNO_ANDROID_BACKEND    -c -o load_policy.o load_policy.c
load_policy.c: In function 'selinux_mkload_policy':
load_policy.c:136:11: error: assignment from incompatible pointer type [-Werror]
  genbools = sepol_genbools;
           ^
cc1: all warnings being treated as errors
make[2]: *** [load_policy.o] Error 1
```

**Comment by stephensmalley** [comment]
Likely a mismatch between your system libsepol headers and the upstream ones.  libselinux needs to be built against the upstream libsepol headers.  Try building with make DESTDIR=/path/to/dest install to build and install each component to a private destination directory.

**Comment by ssbarnea** [comment]
@stephensmalley Thanks. I am wondering if there is any chance of making selinux python bindings installable using pip. Pip wheel do support binary packages even for linux via manylinux but I am not sure if selinux could be covered by this.

The reason for this is because at this moment selinux python extension is not available to python virtualenvironments and there is no easy way to install it. In fact the only "succeeses" where to manually copy selinux files from the system python to the virtualenv.... which clearly does not scale.

I am even considering trying to use a placeholder selinux pure-python package that loads the native one by detecting its location at runtime. Python virtualenvs are not really sandboxed which means that the python module is unrestricted to discover the real selinux package and to import it. I am not sure if this may ever work.

**Comment by stephensmalley** [comment]
I'm afraid I don't know the answer or what would be involved.  Maybe take it up on the selinux mailing list, selinux@vger.kernel.org.

**Comment by fishilico** [comment]
Hi, using pip and virtualenv are two distinct subjects:

- It is quite hard to support installing SELinux's python bindings using pip because they depends on library that needs to be available on the system (at least `libsepol.so` and `libselinux.so`). These libraries are to part of the SONAMEs listed in https://www.python.org/dev/peps/pep-0513/#the-manylinux1-policy so, as far as I understand, this blocks SELinux's python bindings from being a package that can be installed by pip.

- Using virtualenv with SELinux's python bindings is possible. It is actually what the Travis-CI configuration of this repository does. The environment setup looks quite complex in order to grab `Python.h`, which is required to compile the modules: https://github.com/SELinuxProject/selinux/blob/891cfee44f7af80ea87c10991058f9d5b66ae96e/.travis.yml#L95-L99

Anyway, in order to make SELinux's python bindings work, they need to match the version of the installed `libsepol.so` and `libselinux.so` in some way. A straightforward way of ensuring this is to install the packages of your distribution and to create a virtualenv using: `virtualenv --system-site-packages`.

**Comment by ssbarnea** [comment]
While I do use ``--system-site-packages`` in many places this is quite an controversed option and a huge number of users prefer to avoid it during QA/testing.

What we need to do here is to assure that we publish selinux bindings on pypi, even if that is only as as source, allowing users to add 'selinux' as a conditional dependency.
