### ISSUE TITLE
libsepol services symbols not exported

### ISSUE THREAD

**Issue by garyttierney** [SELinuxProject/selinux#153]
Is there any reason why the majority of the symbol definitions for the API declared in `sepol/policydb/services.h` are hidden? E.g., https://github.com/SELinuxProject/selinux/blob/master/libsepol/src/services.c#L1280.

I've been using BPF to trace `avc_has_perm` calls in the kernel (so I can get kernel and userspace stacktraces) and need to translate SIDs to security contexts. The services API exports a symbol that allows me to select the policy used for all of these subsequent calls (`sepol_set_policydb_from_file`), but none of symbols for those calls are exported.

I wonder if I'm missing some deprecation notice from the past or any rationale behind why these APIs are hidden. `checkpolicy` seems to use these symbols by statically linking in libsepol.

**Comment by garyttierney** [comment]
Ah, looking closer at the sidtab structure I couldn't use these APIs anyway since contexts are interned to SIDs on the fly in the kernel, so I suppose I'd have to do the translation in-kernel. I can do this with an out-of-tree kmod and do the translation calls over netlink, but I wonder if there's a better way to go about it?

I'll leave this issue open, but I suppose it's now more about why `sepol_set_policydb_from_file` is exported (unintentionally?).

**Comment by stephensmalley** [comment]
libsepol was originally created by ripping the core data structures and code out of checkpolicy and putting them into a library for reuse by additional components.  checkpolicy itself remains tightly coupled and therefore uses the static lib. At the same time we didn't want to turn the policydb data structures and all of the internal APIs into a stable shared library ABI/API that would have to be versioned and maintained forever (beyond the existing binary policy format versioning).  So we wrapped the data structures with opaque ones (e.g. include/sepol/policydb.h defines an opaque struct sepol_policydb and a stable library API/ABI for operating on it, which wraps the internal include/sepol/policydb/policydb.h struct policydb and a subset of its hidden APIs).  Users of the shared library are limited to the definitions and interfaces exposed by include/sepol/*.h, not anything under include/sepol/policydb/*.h.  sepol_set_policydb_from_file() is exposed to support users of the shared library such as setfiles -c, chkcon, and sefcontext_compile -p that load a kernel binary policy and then check file context validity against it via sepol_check_context(); this does not expose policydb internals outside the library.
As you said, it wouldn't help to export the libsepol sidtab since SIDs are dynamically allocated on demand. Kernel SIDs are not exposed to userspace in order to permit the kernel to reclaim them if no longer in use (although such support is not implemented in the kernel currently and would require fairly significant changes outside of just SELinux to enable tracking their lifecycle since SIDs leak into other subsystems such as audit and networking) and to allow their implementation to be changed if needed (e.g. extended to 64 bits, although this likewise would require expanding networking data structures in a manner unlikely to win friends from the networking maintainers).  We have tossed around experimental patches in the past to expose them via selinuxfs for testing/debugging purposes (e.g. adding a sid2context node and a context2sid node that expose security_sid_to_context() and security_context_to_sid(), along with an nsid node to expose the current number of allocated SIDs) but I can't seem to put my hands on one of those patches at the moment.

**Comment by garyttierney** [comment]
Ah, thanks for the comprehensive explanation on the exported symbols. I missed that there were some others in there that were also exported (notably `sepol_check_context`).

I'd much prefer an selinuxfs interface to do this as opposed to my LKM suggestion, but I can't see a use case outside of translating SIDs for something like my BPF tracing code. I'm happy to provide an updated patch if this is something that could land upstream, though I couldn't find existing patches for this in the archives. I'll continue this discussion on the mailing list.
