### ISSUE TITLE
URL in man page leads to 404

### ISSUE THREAD

**Issue by cherdt** [SELinuxProject/selinux#170]
The following URL is referenced in numerous files:

http://www.nsa.gov/research/selinux

However, that page is currently producing a 404 error.

This page may be the current version:

https://www.nsa.gov/What-We-Do/Research/SELinux/

**Comment by bachradsusi** [comment]
https://www.nsa.gov/What-We-Do/Research/SELinux/ says it's not been updated since 2008 and points to this github project - https://github.com/SELinuxProject
Also another site selinuxproject.org states it's somewhat historical and points to this project as well.  

So I'd use https://github.com/SELinuxProject

www.nsa.gov seems to be only checkpolicy, checkmodule man pages where it points to "Configuring the SELinux Policy" so it could be changed to https://github.com/SELinuxProject/refpolicy/wiki

There's also www.nsa.gov in python/sepolgen/HACKING:

    [selist]: https://www.nsa.gov/What-We-Do/Research/SELinux//info/list.cfm

I guess it would be better to use https://github.com/SELinuxProject/selinux/wiki/Contributing

@stephensmalley what do you think?

**Comment by stephensmalley** [comment]
Concur, we should stop referring to nsa.gov and selinuxproject.org and try to be more proactive in maintaining/augmenting the github wiki pages.
