### ISSUE TITLE
add restorecon option to not cross filesystem boundaries?

### ISSUE THREAD

**Issue by qralston** [SELinuxProject/selinux#208]
Before I kick this idea to the mailing list, let alone work on a patch: would it be reasonable to add an option to `restorecon` to not cross filesystem boundaries?

We would like to periodically run `restorecon` on all core filesystems (`/`, `/home`, `/var`, et. al.) on all of our hosts, in order to find and correct (inevitable) file security context drift. But we have multiple hosts with large local filesystems, and we don't want `restorecon` to spend hours/days descending into those filesystems. And we don't always know in advance what the file paths to those filesystems will be.

The way many utilities solve this problem is to provide an option to not cross filesystem boundaries. E.g., `find` has `-xdev`, `du` has `-x`, et. al.

Would it be reasonable to add an `-x` option to `restorecon`, to make it not cross filesystem boundaries?

Or is there a better way to prevent `restorecon` from getting lost in multi-terabyte local filesystems?

**Comment by stephensmalley** [comment]
setfiles and restorecon are the same program these days with different user interfaces and defaults (setfiles was the original SELinux file labeling utility, restorecon was created by Red Hat and later folded back into setfiles since it heavily overlapped in functionality).  setfiles defaults to xdev behavior.  Internally, this is just done by setting SELINUX_RESTORECON_XDEV flag before calling the libselinux selinux_restorecon() function.  So adding it to restorecon is just a matter of adding a command line option to enable it and setting r_opsts.xdev to SELINUX_RESTORECON_XDEV in that case.

**Comment by bachradsusi** [comment]
> Before I kick this idea to the mailing list, let alone work on a patch: would it be reasonable to add an option to `restorecon` to not cross filesystem boundaries?

 FYI mailing is not only for patches, it's used for discussions, solving problems, ... There's a bigger audience as not everybody follows github issues.

**Comment by qralston** [comment]
@bachradsusi: understood. I have been plowed under with higher-priority work the past few weeks, but when I get back to this, I will post to the mailing list.

**Comment by PeterWhittaker** [comment]
Would it be better to propose these changes to the ML than as PRs?

**Comment by bachradsusi** [comment]
Yes, please. See "Contributing Code" at https://github.com/SELinuxProject/selinux/blob/master/CONTRIBUTING.md

**Comment by PeterWhittaker** [comment]
Wilco. Might take me a bit....

**Comment by PeterWhittaker** [comment]
Done. Correctly, I hope.

**Comment by PeterWhittaker** [comment]
NOW it should be done correctly....
