### ISSUE TITLE
Incompatibility with policy db version 30

### ISSUE THREAD

**Issue by MSF-Jarvis** [SELinuxProject/selinux#21]
I am an Android developer, and the AOSP guidelines regarding SELinux [here](https://source.android.com/security/selinux/validate.html) suggest the use of the `audit2allow` tool, which I believe originates from this repository. My sample run went something like this : 

```shell
$ adb shell su root dmesg | audit2allow -p sepolicy 
libsepol.policydb_read: policydb version 30 does not match my version range 15-29
invalid binary policy sepolicy
```

Is there any way I can work around this? It'd be a real bother to build a sepolicy with policydb version 29 to begin testing and fixing denials

**Comment by williamcroberts** [comment]
You need to use the one that is built with the Android source tree. To verify which audit2allow should not point to the system installed one but rather to the one in the Android tree.

Example of Bad:
$ which audit2allow
/usr/bin/audit2allow

Example of Good:
$ which audit2allow 
/build/wcrobert/aosp/external/selinux/prebuilts/bin/audit2allow

**Comment by MSF-Jarvis** [comment]
Thanks a lot sir, I'll give that a shot. Appreciate the quick response.

**Comment by williamcroberts** [comment]
Next time hit the mailing list for seandroid, instructions here:
http://seandroid.bitbucket.org/ForMoreInformation.html

**Comment by MSF-Jarvis** [comment]
Thanks again :)

**Comment by tarunkapadia93** [comment]
go to source code dir

export ANDROID_BUILD_TOP=$(pwd)

adb shell su root dmesg | ./external/selinux/prebuilts/bin/audit2allow -p out/target/product/<device>/root/sepolicy

**Comment by MSF-Jarvis** [comment]
Erm, been ages since this got resolved, but I appreciate your effort :)

**Comment by Arunakar-B** [comment]
Hi all.. I followed the suggestions posted in this page. But I still see the following error. 

M93p:~/APQ8016_410C_LA.BR.1.2.7-01010-8x16.0_6.0.1_Marsh_Mallo_P2/external/selinux/prebuilts/bin$ export ANDROID_BUILD_TOP=$(pwd)

M93p:~/APQ8016_410C_LA.BR.1.2.7-01010-8x16.0_6.0.1_Marsh_Mallo_P2/external/selinux/prebuilts/bin$ dmesg | audit2allow -p ../../../../out/target/product/msm8916_64/root/sepolicy 

**libsepol.policydb_read: policydb version 30 does not match my version range 15-29

invalid binary policy ../../../../out/target/product/msm8916_64/root/sepolicy**

Pls can you help me in resolving the issue.

**Comment by stephensmalley** [comment]
I see two problems with what you show above:
1. You set ANDROID_BUILD_TOP from the external/selinux/prebuilts/bin subdirectory instead of from the top-level AOSP source directory. Also, I think you are better off just running lunch to set up your environment; you need more than just ANDROID_BUILD_TOP - you also need ANDROID_HOST_OUT (at least in AOSP master, maybe not in 6.0.1).
2. You ran dmesg on the build host, so you aren't going to get denials from your device that way. Note that the earlier examples ran it via adb shell so that they were getting log messages from the device.  Also, I think these days you can just grab logcat output and that should include avc: denied messages too, except maybe for early boot messages.

**Comment by shravan77** [comment]
Hi Stephen. Please can you let me know where am I going wrong.
1. I downloaded the AOSP build (Android version 6.0.1) for Dragonboard 410c and compiled it. 
2. Flashed the images and checked the status of Selinux using getenforce.
3. In permissive mode I collected the denials logs using adb logcat command.
4. I tried to create a policy file from denial logs list using audit2allow command. Resulting to the above command, I got following error.
      _**libsepol.policydb_read: policydb version 30 does not match my version range 15-29**_
I went through following solutions to resolve the issue:
1. Instead of using /usr/bin/audit2allow I used .external/selinux/prebuilts/bin/audit2allow
2. I also used other path : ./external/selinux/policycoreutils/audit2allow/audit2allow
3. Applied Android patch for policydb version 30. Followed cherry pick method to apply the patch.

Still I'm seeing the error. I'm also unable to use sedispol and seinfo tools as I'm getting not found message. I'm stuck up here. Pls help.

**Comment by stephensmalley** [comment]
You need to run lunch (with appropriate arguments).  Then your environment will be set up to use the AOSP-built versions of audit2allow and libsepol, not the distribution-provided ones, and you shouldn't need to specify a path at all.  If you still have problems, take it up on seandroid-list mailing list.
