### ISSUE TITLE
swig warnings

### ISSUE THREAD

**Issue by williamcroberts** [SELinuxProject/selinux#222]
We may want to investigate some of these swig warnings:

```
swigging selinuxswig_python.i to selinuxswig_python_wrap.c
swig -python -o selinuxswig_python_wrap.c selinuxswig_python.i
../include/selinux/avc.h:414: Warning 302: Identifier 'avc_cache_stats' redefined (ignored),
../include/selinux/avc.h:394: Warning 302: previous definition of 'avc_cache_stats'.
../include/selinux/selinux.h:143: Warning 451: Setting a const char * variable may leak memory.
../include/selinux/selinux.h:378: Warning 451: Setting a const char * variable may leak memory.
```

**Comment by cgzones** [comment]
`avc_cache_stats` is a struct and a function:

https://github.com/SELinuxProject/selinux/blob/091549b2d0d45899442c9725d219b7dd191036bb/libselinux/include/selinux/avc.h#L394-L414

**Comment by williamcroberts** [comment]
> `avc_cache_stats` is a struct and a function name:
> 
> https://github.com/SELinuxProject/selinux/blob/091549b2d0d45899442c9725d219b7dd191036bb/libselinux/include/selinux/avc.h#L394-L414

So Swig is just being overly noisy and dumb. Thanks.

**Comment by cgzones** [comment]
There might be an actual problem here:
I am not a python expert by I think there is no python wrapper generated for the function `avc_cache_stats()`.

We might not be able to change either name due to backwards-compatibility.
(maybe we have to add a new function `avc_get_cache_stats()` which calls internally `avc_cache_stats()`?)
