### ISSUE TITLE
Usage of #!/usr/bin/python3 -Es

### ISSUE THREAD

**Issue by cgzones** [SELinuxProject/selinux#236]
Several python scripts use the shebang `#!/usr/bin/python3 -Es`.

This renders them unusable with a build in a custom destination directory.
(`-E` prevents custom PYTHONPATH's)

Is this intended?

**Comment by fishilico** [comment]
The intent is to make system commands (like `/usr/sbin/semanage`) use the library installed system-wide, because this script has a specific label (`semanage_exec_t` in refpolicy).

I haven't looked at the scripts in the project, but if you give some examples of scripts for which it would make sense to allow using `PYTHONPATH` (for example for scripts that are expected to be executed by non-privileged users without a domain transition), the shebang could be modified for them.

**Comment by cgzones** [comment]
I was debugging `sepolgen-ifgen` and just wondered.
Probably we want the final system scripts to ignore custom paths.
