### ISSUE TITLE
Selinux enforcing mode Error 

### ISSUE THREAD

**Issue by pechettibhaskar** [SELinuxProject/selinux#251]
When I installed the Selinux in Ubuntu 14.04 server and In vi /etc/SELinux/config I changing into SELINUX=permissive  to SELINUX=enforcing mode then rebooting my Ubuntu 14.04 server,  where I am not able to login into the server, it showing error  "/bin/bash permission denied".

OS : Ubuntu 14.04

**Comment by stephensmalley** [comment]
The error you are getting is due to the default policy shipped in Ubuntu 14.04 being incomplete/insufficient to work out of the box, which is a bug in the Ubuntu/Debian policy not an upstream SELinux issue (and this particular repository is for the SELinux userspace not the policy anyway).  Ubuntu doesn't directly support SELinux; it just happens to inherit the Debian selinux-related packages and if they don't work, Canonical/Ubuntu doesn't care because they support AppArmor not SELinux.  Debian SELinux wiki pages warn you to not go enforcing without checking your logs and dealing with any residual denials not covered by the default policy; you'll need to create local policy for your particular configuration.  Also Ubuntu 14.04 is quite old so it presumably has very old SELinux packages.
