### ISSUE TITLE
selinux@vger.kernel.org not active anymore

### ISSUE THREAD

**Issue by LM1LC3N7** [SELinuxProject/selinux#269]
Hello,

I tried to send an email to `selinux@vger.kernel.org ` but it seems disabled as I received `Undelivered Mail Returned to Sender`.

It was about an error I found with SELinux and docker when changing the default docker installation path.
It result in an impossibility to start containers, like "alpine", because of SELinux.

I already opened an issue on moby github repo, but without answers for now, where I explain how to reproduce the issue:
https://github.com/moby/moby/issues/41654

Can you check or help me to debug this?

Thanks!

**Comment by bachradsusi** [comment]
According to archives at https://lore.kernel.org/selinux/ the mailing list works as expected. It could be returned due to various reasons, headers might help. 

Given that your problem seems to be related to container_t you should get better support at https://github.com/containers/container-selinux

**Comment by LM1LC3N7** [comment]
Oh yes you are right, I didn't read the returned email but it was clearly written:
> Content-Policy reject msg: The message contains HTML subpart, therefore we
consider it SPAM or Outlook Virus. TEXT/PLAIN is accepted.! 

Whatever I am opening an issue to container-selinux instead, it might be more related.
