### ISSUE TITLE
Introduce release tag for the whole project

### ISSUE THREAD

**Issue by HuKeping** [SELinuxProject/selinux#270]
Can we introduce a release tag `3.0` for the whole project? At present there are only release tag for components, like `libselinux-3.0`

Thanks.

**Comment by bachradsusi** [comment]
The current release tag for the whole project is  [20200710](https://github.com/SELinuxProject/selinux/tree/20200710) I guess the reason for this was that sepolgen used to have a different version than other components before 20161014. Since then sepolgen was merged to python and I gues it's not really necessary to use date for release tag.

But this needs to be discussed at selinux@vger.kernel.org list first, see https://github.com/SELinuxProject/selinux/blob/master/README.md and https://github.com/SELinuxProject/selinux/blob/master/CONTRIBUTING.md

**Comment by HuKeping** [comment]
Hi @bachradsusi , would you mind if send an email to the mailing list. I've got some problem to subscribe  `selinu@vger.kernel.org` due to the company proxy problem.

**Comment by HuKeping** [comment]
#271 merged, closing.
