### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by cgzones** [SELinuxProject/selinux#299]
It seems like the travis-ci.com integration does not work anymore, as the last build is from [May 12th](https://travis-ci.com/github/SELinuxProject/selinux/builds).

I stumbled over it because the status badge still points to Travis and not the GitHub Actions (https://github.com/SELinuxProject/selinux/blob/master/README.md#L5).

**Comment by fishilico** [comment]
Yes, it seems that Travis CI has issues with open-source projects. Some work has been done to migrate the CI to GitHub Actions. At first Travis CI was kept to run the SELinux testsuite in a QEMU virtual machine, because GitHub Actions did not support virtualization directly, but  now that the action ["Run SELinux testsuite in a virtual machine"](https://github.com/fishilico/selinux/actions/workflows/vm_testsuite.yml) has been working fine for some time (using Vagrant on mac OS workers), we can safely remove all the parts related to Travis CI from https://github.com/SELinuxProject/selinux.

Do you want to send patches related to this to the SELinux mailing list? (I see at least two things to do: update the README badges to the GitHub Actions workflows, and remove `.travis.yml`)

Thanks
