### ISSUE TITLE
a suspicious integer overflow in libselinux/src/compute_user.c : 54

### ISSUE THREAD

**Issue by shqking** [SELinuxProject/selinux#47]
Hello.

A suspicious integer overflow is found in libselinux/src/compute_user.c : 54.
The source code is here. (https://github.com/SELinuxProject/selinux/blob/master/libselinux/src/compute_user.c#L54)

If variable "nel" can be crafted as 0xffff ffff, the integer addition at line 54 would overflow to 0, leading to no memory space allocated. This would further lead to buffer overflow at line 62 in a loop. Note that vulnerable "nel" is read from a file "selinux_mnt/user", following the path, i.e. line 27, line 28, line 45 and line 49.

Since I'm not an expert in the source code of libselinux, I'm not sure whether "nel" can be assigned with that very big integer (0xffff ffff). If so, this issue is a severe bug definitely. If not, it is a false positive and please ignore it.

Thanks a lot.

**Comment by stephensmalley** [comment]
nel is read from a kernel pseudo file (/sys/fs/selinux/user, part of selinuxfs pseudo filesystem), so only the value originates from the kernel.  The kernel in turn computes nel from the security policy configuration, which can only be loaded by authorized processes.  Further, since nel is the number of elements in the array provided in the remainder of the buffer, and since selinuxfs only allows page-sized reads, a very large nel value will end up causing an error to be returned by the kernel since the array won't fit into the buffer.   So this should never be possible.
That said, happy to take a patch that checks for integer overflow as a precaution.  Patches preferably sent to selinux AT tycho.nsa.gov (subscribe via selinux-join AT tycho.nsa.gov).

**Comment by shqking** [comment]
Thanks for your explanation.
Since it is a false positive, i will close this issue.
