### ISSUE TITLE
lookup_errno during ./build

### ISSUE THREAD

**Issue by TheGrimPredator** [SELinuxProject/selinux#48]
Hello
I receive the following error when attempting to run the build script. 
```
src/basic/errno-from-name.h:143:1: error: conflicting types for ‘lookup_errno’
 lookup_errno (register const char *str, register size_t len)
 ^~~~~~~~~~~~
src/basic/errno-list.c:25:33: note: previous declaration of ‘lookup_errno’ was here
 static const struct errno_name* lookup_errno(register const char *str,
                                 ^~~~~~~~~~~~
make[2]: *** [Makefile:15926: src/basic/libbasic_la-errno-list.lo] Error 1
make[1]: *** [Makefile:21958: all-recursive] Error 1
make: *** [Makefile:9898: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```
I am trying to install SELinux on a ArchLinux VM. How can I resolve this?

**Comment by fishilico** [comment]
Hello,
This is a build error from systemd package, which happens when you build systemd-selinux from the AUR. It has been reported upstream in https://github.com/systemd/systemd/issues/5039, fixed in https://github.com/systemd/systemd/commit/c9f7b4d356a453a01aa77a6bb74ca7ef49732c08, reported in Arch Linux bug tracker (https://bugs.archlinux.org/task/52945) and fixed in systemd-selinux package (https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=systemd-selinux&id=8a045049d387189eea6137f5fcc152fc6daa524d and https://github.com/archlinuxhardened/selinux/commit/8a045049d387189eea6137f5fcc152fc6daa524d).

How are you building SELinux packages?
