### ISSUE TITLE
fcontext rules for sockets break semanage export

### ISSUE THREAD

**Issue by seidler2547** [SELinuxProject/selinux#49]
I am using CentOS 7, policycoreutils 2.5.

Whenever a custom fcontext rule with file type **"socket"** is added, `semanage fcontext -E` stops working until the rule is removed. This is particularly unfortunate for me as it breaks Puppet which relies on the export functionality to determine whether a rule needs to be added or not.

### Steps To Reproduce:
1. Run `semanage fcontext -E` <br/> → output is correct, shows custom rules
1. Run `semanage fcontext -a -f s -t httpd_var_run_t '/var/apps/\.sockets(/.*)?'`
1. Run `semanage fcontext -E`<br/> → prints "KeyError: socket"

### Cause
The root cause, from what I can see, is in `seobject.py`

Not sure if that fix is correct or if the lookup is wrong, but when I change the **"s"** value entry in [`file_type_str_to_option`](https://github.com/SELinuxProject/selinux/blob/master/python/semanage/seobject.py#L87) from **"socket file"** to **"socket"**, it works as expected.

My first guess is that the lookup in that hash in line 2134 in my version ([current version here](https://github.com/SELinuxProject/selinux/blob/master/python/semanage/seobject.py#L2099)) either needs to operate on a different hash, or that the input data is wrong, or that simply the hash is wrong and the above change is the correct fix.

**Comment by fishilico** [comment]
In libsemanage, [semanage_fcontext_get_type_str](https://github.com/SELinuxProject/selinux/blob/13cd4c8960688af11ad23b4c946149015c80d549/libsemanage/src/fcontext_record.c#L206) has been returning "socket" for `SEMANAGE_FCONTEXT_SOCK` at least since the initial git import. In seobject.py it is even correctly written in `file_types["socket"] = SEMANAGE_FCONTEXT_SOCK` ([line 73](https://github.com/SELinuxProject/selinux/blob/4791a99d67dd7b3597f58cd1e180f2ac58ec66fd/python/semanage/seobject.py#L73)).

I guess `file_type_str_to_option` should have a mapping between "socket" and "s" instead of using "socket file".

**Comment by stephensmalley** [comment]
Yes, that sounds correct to me as well.  Seems to date back to commit 3c1d51c01a90c1bf8ba26859ea742f689effd036 and successive commits that used it. @rhatdan

**Comment by seidler2547** [comment]
Sounds good. Should I submit a pull request or will you make the change?

**Comment by stephensmalley** [comment]
Feel free to submit a PR and/or post to selinux AT tycho.nsa.gov.

**Comment by stephensmalley** [comment]
If you are unable to submit a patch, just let us know and we'll take care of it.
