### ISSUE TITLE
Documentation regarding user passed in APIs may need to be more explicit

### ISSUE THREAD

**Issue by github-user-7** [SELinuxProject/selinux#70]
When attempting to utilize the built in busybox support for SELinux, which relies on libselinux, it was not allowing users to log in, failing to get SID for user.  I am brand new to SELinux so I could be wrong, but after much debugging it appears to me that the get_default_context() API that busybox is using requires an SELinux user to be passed in, not a regular Linux username.  Looking at the man page for this API, it is not clear to me what kind of user is expected to be passed in.  Could the documentation please be updated to specify this, if I am correct in believing that it is expecting to receive SELinux users only?  busybox is passing in the login username (regular Linux user account), so I updated busybox to call getseuserbyname() before the call to get_default_context() so it passes in the seuser and now it is working.  This is similar to what PAM library appears to do for a similar call to get a default content.  If busybox implementation is incorrect, I can only assume it is because of the lack of clarity in the documentation.  Or perhaps libselinux used to do that username translation inside get_default_context()?

Thanks for looking.

**Comment by stephensmalley** [comment]
SELinux has changed behavior in this area over time, so the busybox implementation may have been correct when it was first implemented.  Originally there was no getseuserbyname() at all, and one was expected to define a SELinux user in policy for each Linux user.  This was however impractical, so libselinux started falling back to a default SELinux user (user_u) if there was no matching SELinux user for the Linux user.  This however was also found to be insufficient, so seusers and getseuserbyname() was introduced as a layer of indirection between Linux users and SELinux users.  Then it appears that someone removed the default fallback of user_u within libselinux since it was no longer being used and could lead to surprising results if no context was available for the original user. So that's the history.
I agree that the man page could use an update.  However, I would actually like to completely overhaul this logic; this has been discussed on the selinux mailing list a number of times but no one has gotten a round tuit yet.

**Comment by github-user-7** [comment]
OK, thanks for the detailed information.  Would you like me to close this issue noting that you have plans to reorganize this part of the library, or would you be using this open issue to track those changes?

**Comment by stephensmalley** [comment]
You can leave it open to track the man page update; the actual change in logic is already noted in #28
